import { Property,formatAmount,formatDate } from '@/lib/domain';
import { PropertyControls } from './property-controls';
export function StatusBadge({status}:{status:Property['status']}) {return <span className={`status ${status}`}><i aria-hidden="true"/>{status}</span>;}
export function PropertyTable({properties,readOnly=false}:{properties:Property[];readOnly?:boolean}) {
  if(!properties.length) return <section className="empty-state"><div className="empty-icon">▦</div><h2>{readOnly?'No properties yet.':'No properties yet — add your first property.'}</h2><p>{readOnly?'Ask a team owner or editor to add your first property.':'Your values, renewal dates and reminders will appear here.'}</p><PropertyControls add readOnly={readOnly}/></section>;
  return <div className="table-wrap property-list"><table className="property-table" role="table" aria-label="Property values and renewal schedule"><thead><tr role="row"><th scope="col">Property</th><th scope="col" className="numeric">Insured value</th><th scope="col" className="numeric">Refurbishment</th><th scope="col" className="numeric">Updated value</th><th scope="col">Renewal / reminder</th><th scope="col">Status</th>{!readOnly&&<th scope="col" className="property-action-heading">Actions</th>}</tr></thead><tbody role="rowgroup">{properties.map(p=><tr key={p.id} role="row">
    <td className="property-identity" role="cell"><a className="property-name" href={`/properties/${p.id}`}>{p.name}</a><span className="cell-detail">{p.address||'No address'}</span><span className="policy-detail">{p.insurer||'Insurer not set'} · {p.policy_number||'No policy number'}</span></td>
    <td className="numeric insured-cell" role="cell"><span className="mobile-cell-label" aria-hidden="true">Insured value</span>{formatAmount(p.insured_value)}</td><td className="numeric refurbishment-cell" role="cell"><span className="mobile-cell-label" aria-hidden="true">Refurbishment</span>{formatAmount(p.refurbishment_cost)}</td><td className="numeric updated-amount" role="cell"><span className="mobile-cell-label" aria-hidden="true">Updated value</span>{formatAmount(p.updated_value)}</td>
    <td className="date-cell" role="cell"><span className="mobile-cell-label" aria-hidden="true">Renewal date</span>{formatDate(p.renewal_date)}<span className="cell-detail">Reminder {formatDate(p.reminder_date)}</span></td><td className="property-status" role="cell"><StatusBadge status={p.status}/></td>{!readOnly&&<td className="property-actions" role="cell"><PropertyControls property={p}/></td>}
  </tr>)}</tbody></table></div>;
}
