import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
const owner='10000000-0000-4000-8000-000000000001',other='10000000-0000-4000-8000-000000000002',editor='10000000-0000-4000-8000-000000000003',viewer='10000000-0000-4000-8000-000000000004';
async function user(id,email) {await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims',$2,false)",[id,JSON.stringify({sub:id,email})]);}
async function rpc(sql,args=[]) {return (await db.query(sql,args)).rows[0];}
try {
 await db.exec(`create role anon;create role authenticated;create schema auth;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
 grant usage on schema auth to anon,authenticated;grant execute on all functions in schema auth to anon,authenticated;`);
 for(const file of ['0001_init.sql','0002_atomic_renewals.sql','0003_private_teams.sql']) await db.exec(await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));
 assert.equal((await db.query('select * from properties where team_id is null')).rows.length,5,'archive preserved');
 await db.exec('set role anon');
 await assert.rejects(db.query('select * from properties'),/permission denied/);
 await assert.rejects(db.query("select create_team('Takeover')"),/permission denied/);
 await assert.rejects(db.query('select process_property_renewal($1,1,0,0,$2)',[owner,'anon']),/permission denied/);
 await db.exec('set role authenticated');await user(owner,'owner@example.com');
 assert.equal((await db.query('select * from properties')).rows.length,0,'demo inaccessible to first user');
 const a=(await rpc("select create_team('Team A') as id")).id;
 const a2=(await rpc("select create_team('Second A') as id")).id;
 const property=await rpc("insert into properties(team_id,name,insured_value,refurbishment_cost,renewal_date) values($1,'Private Tower',8000000,300000,'2028-02-29') returning *",[a]);
 assert.equal(property.user_id,owner);
 await assert.rejects(db.query('update properties set team_id=$1 where id=$2',[a2,property.id]),/cannot move/);
 const editorToken=(await rpc("select invite_team_member($1,'editor@example.com','editor') as token",[a])).token;
 const viewerToken=(await rpc("select invite_team_member($1,'viewer@example.com','viewer') as token",[a])).token;
 await user(other,'other@example.com');
 const b=(await rpc("select create_team('Team B') as id")).id;
 assert.equal((await db.query('select * from properties')).rows.length,0,'other tenant sees no rows');
 assert.equal((await db.query('select * from teams')).rows.length,1,'only own team');
 await assert.rejects(db.query('insert into properties(team_id,name,renewal_date) values($1,$2,$3)',[a,'Malicious','2030-01-01']),/row-level security/);
 assert.equal((await db.query('update properties set name=$1 where id=$2 returning id',['Attack',property.id])).rows.length,0);
 await assert.rejects(db.query('select process_property_renewal($1,9000000,200000,0,$2)',[property.id,'Attack']),/no longer exists/);
 await assert.rejects(db.query('select accept_team_invitation($1)',[editorToken]),/invited email/);
 await assert.rejects(db.query("select invite_team_member($1,'x@example.com','editor')",[a]),/Only team owners/);
 await assert.rejects(db.query("insert into renewal_records(team_id,property_id,new_insured_value) values($1,$2,1)",[b,property.id]),/not available/);
 await user(editor,'editor@example.com');await db.query('select accept_team_invitation($1)',[editorToken]);
 assert.equal((await db.query('select * from properties')).rows.length,1);
 await assert.rejects(db.query("select manage_team_member($1,$2,'viewer')",[a,owner]),/Only team owners/);
 await db.query('select process_property_renewal($1,9000000,200000,0,$2)',[property.id,'Editor renewal']);
 const history=(await db.query('select * from renewal_records')).rows[0];
 assert.equal(history.team_id,a);assert.equal(history.user_id,editor);assert.equal(Number(history.previous_insured_value),8000000);assert.equal(Number(history.updated_value),9200000);
 await assert.rejects(db.query('update renewal_records set notes=$1',['tampered']),/permission denied/);
 await assert.rejects(db.query('select accept_team_invitation($1)',[editorToken]),/expired or was revoked/);
 await user(viewer,'viewer@example.com');await db.query('select accept_team_invitation($1)',[viewerToken]);
 assert.equal((await db.query('select * from properties')).rows.length,1);assert.equal((await db.query('select * from renewal_records')).rows.length,1);
 await assert.rejects(db.query('insert into properties(team_id,name,renewal_date) values($1,$2,$3)',[a,'Viewer write','2030-01-01']),/row-level security/);
 await assert.rejects(db.query('select add_team_samples($1)',[a]),/viewing only/);
 assert.equal((await db.query("update properties set name='Viewer attack' returning id")).rows.length,0);
 assert.equal((await db.query('delete from properties returning id')).rows.length,0);
 await assert.rejects(db.query('select process_property_renewal($1,10000000,0,1,$2)',[property.id,'Viewer attack']),/row-level security|no longer exists/);
 assert.equal((await db.query('select * from renewal_records')).rows.length,1,'viewer transaction rolls back');
 await assert.rejects(db.query("select manage_team_member($1,$2,'editor')",[a,viewer]),/Only team owners/);
 await user(owner,'owner@example.com');
 const selfToken=(await rpc("select invite_team_member($1,'owner@example.com','viewer') as token",[a])).token;
 await db.query('select accept_team_invitation($1)',[selfToken]);
 assert.equal((await rpc('select team_role($1) as role',[a])).role,'owner','accept does not downgrade existing owner');
 const expiredToken=(await rpc("select invite_team_member($1,'editor@example.com','editor') as token",[a])).token;
 await db.exec('reset role');await db.query("update team_invitations set expires_at=now()-interval '1 second' where token=$1",[expiredToken]);await db.exec('set role authenticated');
 await user(editor,'editor@example.com');await assert.rejects(db.query('select accept_team_invitation($1)',[expiredToken]),/expired or was revoked/);await user(owner,'owner@example.com');
 await assert.rejects(db.query("select manage_team_member($1,$2,'remove')",[a,owner]),/cannot be removed/);
 await db.query("select manage_team_member($1,$2,'remove')",[a,editor]);
 const revoke=(await rpc("select invite_team_member($1,'revoke@example.com','viewer') as token",[a])).token;
 const invitation=await rpc('select id from team_invitations where token=$1',[revoke]);
 await db.query('select revoke_team_invitation($1,$2)',[a,invitation.id]);
 await user(editor,'editor@example.com');assert.equal((await db.query('select * from properties')).rows.length,0,'removed member loses access');
 await assert.rejects(db.query('select accept_team_invitation($1)',[revoke]),/expired or was revoked/);
 await user(owner,'owner@example.com');await db.query('delete from properties where id=$1',[property.id]);
 assert.equal((await db.query('select * from renewal_records')).rows.length,0,'owner delete cascades history');
 await db.query('select add_team_samples($1)',[a2]);
 assert.equal((await db.query('select * from properties where team_id=$1',[a2])).rows.length,3,'samples belong only to selected private team');
 await assert.rejects(db.query('select add_team_samples($1)',[a2]),/empty portfolio/);
 await user(other,'other@example.com');assert.equal((await db.query('select * from teams')).rows[0].id,b);
 console.log('PASS: private-team migration, archive isolation, independent teams, owner/editor/viewer RLS, email-bound single-use invitations, owner guards, access revocation, immutable tenant identity, atomic renewal history and cascade.');
} finally {await db.close();}
